### ISSUE TITLE
SIGSEGV (0xb) on executing java file

### ISSUE THREAD

**Issue by rads284** [ScalableMachinesResearch/JXPerf#2]
Upon trying a code to detect SilentLoad detection, same example as in the publication, a JVM segfault occurs. Please let us know the fix.

> Error:
>  A fatal error has been detected by the Java Runtime Environment:
> 
> SIGSEGV (0xb) at pc=0x00007fc1a2ddc7b3, pid=2105, tid=0x00007fc1a5f9b700
> 
>  JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
>  Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
>  **Problematic frame:
> C  [libagent.so+0x2b7b3]  PerfManager::closeEvents()+0x73
>**
>  Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> 
>  An error report file with more information is saved as:
>  /home/rads284/JXPerf-master/script/hs_err_pid2105.log
> 
> If you would like to submit a bug report, please visit:
> http://bugreport.java.com/bugreport/crash.jsp
> The crash happened outside the Java Virtual Machine in native code.
> See problematic frame for where to report the bug.
>
>

**Comment by pengfei-su** [comment]
Just saw your message. It is fixed. Can you try it again?

**Comment by rads284** [comment]
Still getting the same issue.

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fd9824dec43, pid=15591, tid=0x00007fd985544700

 JRE version: OpenJDK Runtime Environment (8.0_232-b09) (build 1.8.0_232-8u232-b09-0ubuntu1~16.04.1-b09)
 Java VM: OpenJDK 64-Bit Server VM (25.232-b09 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libagent.so+0x2ac43]  PerfManager::closeEvents()+0x73

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/student/JXPerf/hs_err_pid15591.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Aborted (core dumped)

**Comment by pengfei-su** [comment]
I have yet to encounter it. Could you please provide more details (e.g., your command line, test case, JDK version) for me to reproduce the bug?
